package by.voloshchuk.servlet.command;

public enum AsyncCommandName {

    LOAD_AVATAR,
    EDIT,
    UPDATE_USER_DETAIL,
    ERROR,
    EMPLOYEE_REQUIREMENTS,
    SEEK_EMPLOYEES,
    ADD_EMPLOYEE,
    ADD_REQUIREMENT,
    LOAD_PROJECT_USERS,
    ADD_TASK,
    UPDATE_TASK_HOURS,
    UPDATE_TASK_STATUS,
    LOAD_TASKS_INFORMATION,
    LOAD_PROJECT_REQUIREMENTS,
    ACCEPT_PAYMENT,
    UPDATE_USER_STATUS
}
