package by.voloshchuk.servlet.command;

public enum CommandName {

    ERROR,
    MAIN,
    ABOUT,
    PROJECTS,
    TO_CREATE_PROJECT,
    CREATE_PROJECT,
    CREATE_TECHNICAL_TASK,
    TO_CREATE_REQUIREMENT,
    TO_SEEK_EMPLOYEES,
    TO_TASKS,
    TECHNICAL_TASKS,
    TO_CREATE_TECHNICAL_TASK,
    FIND_TECHNICAL_TASKS,
    BILLS,
    LOCALE,
    REGISTRATION,
    REGISTRATE,
    AUTHORIZATION,
    AUTHORIZE,
    PROFILE,
    LOGOUT

}
